import { JobCategory } from "./JobTitles";

export const Questions: Record<JobCategory, string[]> = {
    [JobCategory.General]: [
        'Tell me about yourself.', 
        'What is your greatest strength?', 
        'What is your greatest weakness?', 
        'Why should we hire you?', 
        'Why do you want to work here?', 
        'Tell me about a time you showed leadership',
        'Tell me about a time you were successful on a team',
        'What would your coworkers say about you?',
        'Why do you want to leave your current role?',
        'Describe your most challenging project',
        'Tell me about something you have accomplished that you are proud of.',
        'Can you explain your employment gap?',
        'What are your salary expectations?',
        'What do you like to do outside of work?',
        'Tell me about a time you had to manage conflicting priorities',
        'Where do you see yourself in five years?',
        'Describe your leadership style',
        'Tell me about a time you failed or made a mistake.',
        'Tell me about a time you worked with a difficult person.',
        'Tell me about a time you disagreed with someone..',
        'Tell me about a time you created a goal and achieved it.',
        'Tell me about a time you surpassed people\'s expectations.',
        'Tell me about a time you had to handle pressure.',
        'Tell me about a time you had to learn something quickly.',
        'Tell me about a time you had to persuade someone.',
        'Do you have any questions for me?'],
    [JobCategory.AccountExecutive]: ['Sales Executive', 'Account Manager', 'Client Services Executive', 'Business Development Manager', 'Key Account Manager', 'Other'],
    [JobCategory.Accountant]: ['Tax Accountant', 'Forensic Accountant', 'Cost Accountant', 'Auditor Accountant', 'Financial Accountant', 'Other'],
    [JobCategory.BusinessAnalyst]: ['Systems Analyst', 'Business Systems Analyst', 'Process Analyst', 'Data Analyst', 'Financial Analyst', 'Other'],
    [JobCategory.CorporateFinance]: ['Financial Analyst', 'Treasury Analyst', 'Corporate Development Manager', 'Financial Planner', 'Mergers & Acquisitions Analyst', 'Other'],
    [JobCategory.CustomerSuccessManager]: ['Customer Experience Manager', 'Client Success Specialist', 'Customer Support Manager', 'Account Success Manager', 'Customer Retention Specialist', 'Other'],
    [JobCategory.InvestmentBanker]: ['Mergers & Acquisitions Analyst', 'Equity Research Analyst', 'Capital Markets Associate', 'Investment Banking Associate', 'Structured Finance Analyst', 'Other'],
    [JobCategory.MarketingManager]: ['Digital Marketing Manager', 'Product Marketing Manager', 'Content Marketing Manager', 'Brand Manager', 'Market Research Manager', 'Other'],
    [JobCategory.ProjectManager]: ['Scrum Master', 'Project Coordinator', 'Program Manager', 'Agile Project Manager', 'Construction Project Manager', 'Other'],
    [JobCategory.RelationshipManager]: ['Client Relationship Executive', 'Business Development Manager', 'Customer Relationship Manager', 'Account Relationship Manager', 'Partnership Manager', 'Other'],
    [JobCategory.SaleDevelopmentRepresentative]: ['Business Development Representative', 'Inside Sales Representative', 'Lead Qualification Specialist', 'Sales Prospector', 'Outbound Sales Representative', 'Other'],
    [JobCategory.SoftwareEngineer]: [
        '', 
        'Backend Developer', 
        'Full Stack Developer',
        'DevOps Engineer',
        'Mobile App Developer',
        'Other'],
    [JobCategory.WealthManager]: ['Investment Advisor', 'Portfolio Manager', 'Financial Planner', 'Private Banker', 'Estate Manager', 'Other'],
};